language: java
sudo: false

jdk:
- oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer

install: true
script: ./travis.sh
env:
  - TEST=ci

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
    - secure: "eB4XQvyEmKH20QdVSSd2eV7o4zu2cJOekqlmCn572QfY+TwWx9xGWCuOFRSuDTJhl8WB/qSzqFSjAWCqQgRMaODWjAR3yzvJ4v3TRBEZnw8IhLVO33O5sZevCFMVl8kdsuaeUmM2d+A6/rjpWfixc0NnZRify0ZfK+1dkHoR1K0="
